### PR TITLE
feat: added canadian resorts with ikon and epic details

### PR DESCRIPTION
**Pull request by allenkaplan**
Hey! Great project! 

## **What**
I added the Canadian resorts into the map to make this a full North American map

## **Details**

- I also added the Ikon and Epic pass info
- I did not add ski maps nor webcams
- this lowers `Every U.S. Ski Resort Progress` as it uses `allData` --> this can be fixed by change text to `Every NA Ski Resort Progress` OR adding a filter to the calculation (either add new Country field OR exclude Canadian regions/states)

## **How**
I got the Canadian data by 
1. moving the data from `allData.js` to a json file `allData.json` a
2. jq with the following command (pbcopy puts it in the clipboard):

```
cat globalData.json | jq '.[] | select(.country == "Canada")' | jq '.mapLink += ""' | jq '.webcam |= .+ []' | jq '.state = .region' | jq '.resortReview += { "score": "", "link": "", "note": "", "price": "", "easeOfAccess": "", "lodging": "", "chairLifts": "", "runs": "", "terrainPark": "", "food": "", "employees": "", "views": "", "wouldIGoBack": "" }' | jq '.' | jq -s | pbcopy
```

3. appending the output at the end of `allData` in `allData.js`

## **Tests**
open the toggle bellow for before/after

<details>
<summary>Image Comparison</summary>

# **Old**
image

# **New**
image

# **New - Ikon example**
image

</details>

### CODE REVIEW

**Review by Shellnut — CHANGES_REQUESTED** [review]
Dude! This is awesome. Thanks so much for doing this. Unfortunately this is going to need some fine tuning before I can approve it. By adding the Canadian resorts to `alldata.js`, it messes with the U.S. metrics.

image

The way to do this will be by manipulating the global data

image

image

**Comment by allenkaplan** [comment]
Instead of forcing the load of `globalData`, I now have `canadaData` in a separate list. allData is now usData. Now `var allData = usData.concat(canadaData)`

you can see the stats are now unchanged with a swap of `allData` to `usData` in 1 part of `index.html`

also I removed the canadians from global as they were duplicates

image

**Comment by Shellnut** [comment]
Hey I really like what you did here! I ended up going a slightly different direction so that your logic will scale to all of the resorts in the world. I used a lot of your code here: https://github.com/Shellnut/Buckhouse/pull/11. I also wanted to keep the home page somewhat clean to just the U.S. resorts.

I added all of the epic/ikon resorts globally (if you sort by ikon/epic, it will show US+Canada+Europe+etc.)

I also separated out all of the countries so that the next step will be to have filters that can filter by country or continent.
[X] North America
[  ] South America
[  ] Europe
etc.

**Comment by allenkaplan** [comment]
> Hey I really like what you did here! I ended up going a slightly different direction so that your logic will scale to all of the resorts in the world. I used a lot of your code here: https://github.com/Shellnut/Buckhouse/pull/11. I also wanted to keep the home page somewhat clean to just the U.S. resorts.
> 
> I added all of the epic/ikon resorts globally (if you sort by ikon/epic, it will show US+Canada+Europe+etc.)
> 
> I also separated out all of the countries so that the next step will be to have filters that can filter by country or continent.
> [X] North America
> [  ] South America
> [  ] Europe
> etc.
> 
> 

Cheers, thanks for the work! 🍻

**Pull request closed without merging**
